---
- name: Check if MySQL is installed
  stat: path=/etc/init.d/mysql
  register: mysql_installed

- name: Ensure MySQL Python libraries are installed.
  apt: name=python-mysqldb state=latest
  when: mysql_installed.stat.exists == false

- name: Ensure MySQL packages are installed.
  apt: name={{ item }} state=latest
  with_items:
   - mysql-server
   - mysql-common
  when: mysql_installed.stat.exists == false

- name: Stop mysql
  service:
    name=mysql
    state=stopped

- name: Copy user my.cnf file with root passwd credentialsm, skipping grants
  template: 
    src=.my.cnf.j2
    dest=/root/.my.cnf
    owner=root
    group=root
    mode=0600
  tags: mysql


- name: Start mysql
  service:
    name=mysql
    state=started

# - name: Update MySQL root password for localhost root account
#   shell: >
#     mysql -NBe
#     "UPDATE mysql.user SET authentication_string = PASSWORD('{{ lookup('password', 'credentials/' + inventory_hostname + '/mysqlpassword length=20 chars=ascii_letters,digits,hexdigits,punctuation') }}') WHERE User = 'root' AND Host = 'localhost';
#     FLUSH PRIVILEGES";

- name: Apply mysql root password
  mysql_user:
    name=root
    password="{{ lookup('password', 'credentials/' + inventory_hostname + '/mysqlpassword length=20 chars=ascii_letters,digits,hexdigits,punctuation') }}"

- name: Change Root Password
  mysql_user:
    name=root
    host={{item}}
    password="{{ lookup('password', 'credentials/' + inventory_hostname + '/mysqlpassword length=20 chars=ascii_letters,digits,hexdigits,punctuation') }}"
    state=present
    priv=*.*:ALL
  with_items:
    - "{{ inventory_hostname | lower}}"
    - 127.0.0.1
    - ::1

- name: Disallow root login remotely
  command: 'mysql -NBe "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: false

- name: Get list of hosts for the root user.
  command: mysql -NBe "SELECT Host FROM mysql.user WHERE User = 'root' ORDER BY (Host='localhost') ASC"
  register: mysql_root_hosts
  changed_when: false
  always_run: true

- name: Update MySQL root password for localhost root account
  shell: >
    mysql -NBe
    "UPDATE mysql.user SET authentication_string = PASSWORD('{{ lookup('password', 'credentials/' + inventory_hostname + '/mysqlpassword length=20 chars=ascii_letters,digits,hexdigits,punctuation') }}') WHERE User = 'root' AND Host = 'localhost';
    FLUSH PRIVILEGES";

- name: Update auth plugins
  shell: >
    mysql -NBe
    "UPDATE mysql.user SET plugin='mysql_native_password';
    FLUSH PRIVILEGES;"

- name: Delete anonymous mysql user
  mysql_user:
    name=""
    state=absent
  tags: mysql

- name: Remove skip grants
  lineinfile:
    dest=.my.cnf
    regexp="skip-grant-tables"
    state=absent
  tags: mysql

- name: Remove mysql test database
  mysql_db:
    name=test
    state=absent
  tags: mysql
  notify:
    - Restart mysql